import Anthropic from "@anthropic-ai/sdk";
import type { Message } from "@anthropic-ai/sdk/resources/messages/messages";
import { defaultLocale, localizeOhaengLabel, type AppLocale } from "@/lib/i18n";
import { reportSectionDefinitions } from "@/lib/report-builder";
import type { BirthInput, SajuData } from "@/lib/saju/types";
import type { ReportSectionData } from "@/types";

const anthropicModel = "claude-sonnet-4-6";
const anthropicTimeoutMs = 60_000;
const anthropicRetryCount = 2;
const anthropicRetryDelayMs = 1_000;
const anthropicMaxTokens = 4_096;
const sectionFieldOrder = [
  "basic_info",
  "personality",
  "career",
  "romance",
  "health",
  "yearly_fortune",
  "advice",
] as const;

let anthropicClient: Anthropic | null = null;

function getCurrentYear() {
  return new Date().getFullYear();
}

function formatBirthInput(input: BirthInput, locale: AppLocale) {
  if (locale === "en") {
    return [
      `- Birth year: ${input.birthYear}`,
      `- Birth month: ${input.birthMonth}`,
      `- Birth day: ${input.birthDay}`,
      `- Birth hour: ${input.birthHour === null ? "Unknown" : `${input.birthHour}:00`}`,
      `- Gender: ${input.gender === "female" ? "Female" : "Male"}`,
    ].join("\n");
  }

  return [
    `- 태어난 연도: ${input.birthYear}`,
    `- 태어난 월: ${input.birthMonth}`,
    `- 태어난 일: ${input.birthDay}`,
    `- 태어난 시간: ${input.birthHour === null ? "모름" : `${input.birthHour}시`}`,
    `- 성별: ${input.gender === "female" ? "여성" : "남성"}`,
  ].join("\n");
}

function formatPillar(name: string, pillar: SajuData["pillars"]["year"]) {
  return `- ${name}: ${pillar.cheongan}${pillar.jiji} (${pillar.ohaeng})`;
}

function formatSajuData(sajuData: SajuData, locale: AppLocale) {
  const lines =
    locale === "en"
      ? [
          `- Year pillar: ${sajuData.pillars.year.cheongan}${sajuData.pillars.year.jiji} (${localizeOhaengLabel(sajuData.pillars.year.ohaeng, locale)})`,
          `- Month pillar: ${sajuData.pillars.month.cheongan}${sajuData.pillars.month.jiji} (${localizeOhaengLabel(sajuData.pillars.month.ohaeng, locale)})`,
          `- Day pillar: ${sajuData.pillars.day.cheongan}${sajuData.pillars.day.jiji} (${localizeOhaengLabel(sajuData.pillars.day.ohaeng, locale)})`,
        ]
      : [
          formatPillar("년주", sajuData.pillars.year),
          formatPillar("월주", sajuData.pillars.month),
          formatPillar("일주", sajuData.pillars.day),
        ];

  if (sajuData.pillars.hour) {
    lines.push(
      locale === "en"
        ? `- Hour pillar: ${sajuData.pillars.hour.cheongan}${sajuData.pillars.hour.jiji} (${localizeOhaengLabel(sajuData.pillars.hour.ohaeng, locale)})`
        : formatPillar("시주", sajuData.pillars.hour),
    );
  } else {
    lines.push(
      locale === "en" ? "- Hour pillar: omitted because the birth hour is unknown" : "- 시주: 없음 (태어난 시간을 모름)",
    );
  }

  if (locale === "en") {
    lines.push(
      `- Five-element balance: Wood ${sajuData.ohaengRatio.목}, Fire ${sajuData.ohaengRatio.화}, Earth ${sajuData.ohaengRatio.토}, Metal ${sajuData.ohaengRatio.금}, Water ${sajuData.ohaengRatio.수}`,
    );
    lines.push(`- Day master: ${sajuData.ilgan}`);
    lines.push(`- Supportive element: ${localizeOhaengLabel(sajuData.yongsin, locale)}`);
    lines.push(`- Challenging element: ${localizeOhaengLabel(sajuData.gisin, locale)}`);
  } else {
    lines.push(
      `- 오행 비율: 목 ${sajuData.ohaengRatio.목}, 화 ${sajuData.ohaengRatio.화}, 토 ${sajuData.ohaengRatio.토}, 금 ${sajuData.ohaengRatio.금}, 수 ${sajuData.ohaengRatio.수}`,
    );
    lines.push(`- 일간: ${sajuData.ilgan}`);
    lines.push(`- 용신: ${sajuData.yongsin}`);
    lines.push(`- 기신: ${sajuData.gisin}`);
  }

  return lines.join("\n");
}

function buildSystemPrompt(locale: AppLocale) {
  const sectionSchema = reportSectionDefinitions
    .map(
      (section, index) =>
        locale === "en"
          ? `${index + 1}. Write the "${section.title}" content in natural English with at least 220 characters.`
          : `${index + 1}. "${section.title}" 내용은 220자 이상 한국어 문단으로 작성`,
    )
    .join("\n");

  if (locale === "en") {
    return [
      "You are an expert editor for modern English saju reports.",
      "The output format is enforced by the API structured output schema, so return values only without code fences or prefaces.",
      sectionSchema,
      "The sixth section must include the current year as digits.",
      "If the birth hour is unknown, avoid overconfident statements about the hour pillar.",
      "The last sentence of the seventh section must be exactly 'This report was generated by AI and is intended for reference only.'",
      "Avoid deterministic fate claims, medical or legal certainty, and fear-based language.",
      "Keep the tone warm, specific, and grounded rather than mystical or exaggerated.",
    ].join("\n");
  }

  return [
    "너는 한국어 사주 리포트를 작성하는 전문 에디터다.",
    "출력 형식은 API의 structured output schema로 강제되므로 코드펜스, JSON 설명, 서문 없이 값만 채운다.",
    sectionSchema,
    "6번째 '올해 운세' 섹션에는 반드시 현재 연도를 숫자로 포함한다.",
    "태어난 시간이 없으면 시주 단정 표현을 쓰지 말고 조심스럽게 설명한다.",
    "7번째 '종합 조언' 섹션 마지막 문장은 정확히 '본 리포트는 AI가 생성한 참고용 콘텐츠입니다.' 로 끝낸다.",
    "운명을 단정하는 표현, 의료/법률 확정 표현, 과도한 공포 조장은 금지한다.",
    "문체는 따뜻하고 구체적이며 과장되지 않게 유지한다.",
  ].join("\n");
}

function buildUserPrompt(input: BirthInput, sajuData: SajuData, locale: AppLocale) {
  const currentYear = getCurrentYear();

  if (locale === "en") {
    return [
      `Current year: ${currentYear}`,
      "",
      "[User input]",
      formatBirthInput(input, locale),
      "",
      "[Saju calculation result]",
      formatSajuData(sajuData, locale),
      "",
      "[Additional writing guidance]",
      "- Section 4 should reflect relationship patterns through the lens of the selected gender without sounding stereotypical.",
      "- Section 5 should focus on lifestyle guidance instead of medical diagnosis.",
      "- Section 6 should include first-half/second-half flow and a few key themes for the year.",
      "- Section 7 should include practical advice, cautions, and light luck cues such as direction, color, or number.",
    ].join("\n");
  }

  return [
    `현재 연도: ${currentYear}`,
    "",
    "[사용자 입력]",
    formatBirthInput(input, locale),
    "",
    "[사주 계산 결과]",
    formatSajuData(sajuData, locale),
    "",
    "[추가 작성 지침]",
    "- 섹션 4 '연애 & 결혼운'은 성별에 맞는 관계 묘사를 포함한다.",
    "- 섹션 5 '건강운'은 의료 진단처럼 단정하지 말고 생활 관리 조언 중심으로 작성한다.",
    "- 섹션 6 '올해 운세'는 상반기/하반기 흐름과 핵심 키워드를 포함한다.",
    "- 섹션 7 '종합 조언'은 현재 시점 기준 조언, 주의사항, 행운의 방향/색상/숫자를 포함한다.",
  ].join("\n");
}

function getAnthropicApiKey() {
  return process.env.ANTHROPIC_API_KEY ?? "";
}

function getAnthropicClient() {
  if (anthropicClient) {
    return anthropicClient;
  }

  anthropicClient = new Anthropic({
    apiKey: getAnthropicApiKey(),
    maxRetries: 0,
    timeout: anthropicTimeoutMs,
  });

  return anthropicClient;
}

function buildStructuredOutputSchema(locale: AppLocale) {
  if (locale === "en") {
    return {
      type: "object",
      properties: {
        basic_info: {
          type: "string",
          description: "Saju snapshot in English. Explain pillars, element balance, and useful/challenging elements in 220+ characters.",
        },
        personality: {
          type: "string",
          description: "Natural personality section in English. Cover temperament, strengths, weaknesses, and relationship style in 220+ characters.",
        },
        career: {
          type: "string",
          description: "Career and wealth section in English. Cover aptitude, working style, and money flow in 220+ characters.",
        },
        romance: {
          type: "string",
          description: "Love and marriage section in English. Reflect the selected gender context and relationship rhythm in 220+ characters.",
        },
        health: {
          type: "string",
          description: "Health section in English. Use grounded lifestyle guidance rather than diagnosis, 220+ characters.",
        },
        yearly_fortune: {
          type: "string",
          description: "This-year section in English. Must include the current year as digits plus first-half/second-half flow, 220+ characters.",
        },
        advice: {
          type: "string",
          description:
            "Overall guidance section in English. Include practical advice, cautions, and light luck cues. The final sentence must be 'This report was generated by AI and is intended for reference only.'",
        },
      },
      required: [...sectionFieldOrder],
      additionalProperties: false,
    } as const;
  }

  return {
    type: "object",
    properties: {
      basic_info: {
        type: "string",
        description: "사주 기본 정보. 년주·월주·일주·시주, 오행 비율, 용신/기신을 바탕으로 220자 이상 설명",
      },
      personality: {
        type: "string",
        description: "타고난 성격 & 기질. 일간 기준 성격 분석, 강점과 약점, 대인관계 스타일을 220자 이상 설명",
      },
      career: {
        type: "string",
        description: "직업 & 재물운. 적성, 일하는 방식, 재물 흐름을 220자 이상 설명",
      },
      romance: {
        type: "string",
        description: "연애 & 결혼운. 성별에 맞는 관계 묘사와 배우자/결혼 관련 해석을 220자 이상 설명",
      },
      health: {
        type: "string",
        description: "건강운. 의료 진단처럼 단정하지 않고 생활 관리 조언 중심으로 220자 이상 설명",
      },
      yearly_fortune: {
        type: "string",
        description: "올해 운세. 현재 연도 숫자, 상반기/하반기 흐름, 핵심 키워드를 포함해 220자 이상 설명",
      },
      advice: {
        type: "string",
        description:
          "종합 조언. 현재 시점 기준 조언, 주의사항, 행운의 방향/색상/숫자를 포함하고 마지막 문장은 반드시 '본 리포트는 AI가 생성한 참고용 콘텐츠입니다.' 로 끝나는 220자 이상 설명",
      },
    },
    required: [...sectionFieldOrder],
    additionalProperties: false,
  } as const;
}

function extractResponseText(message: Message) {
  const parts: string[] = [];

  for (const block of message.content) {
    if (block.type === "text") {
      parts.push(block.text);
    }
  }

  return parts.join("\n").trim();
}

function extractJsonText(value: string) {
  const fencedMatch = value.match(/```(?:json)?\s*([\s\S]*?)```/i);

  if (fencedMatch?.[1]) {
    return fencedMatch[1].trim();
  }

  const firstBrace = value.indexOf("{");
  const lastBrace = value.lastIndexOf("}");

  if (firstBrace === -1 || lastBrace === -1 || lastBrace <= firstBrace) {
    throw new Error("Claude response did not contain a JSON object.");
  }

  return value.slice(firstBrace, lastBrace + 1);
}

function parseClaudeSections(rawText: string, locale: AppLocale) {
  const parsed = JSON.parse(extractJsonText(rawText)) as Record<string, unknown>;
  const sections: ReportSectionData[] = sectionFieldOrder.map((field, index) => {
    const definition = reportSectionDefinitions[index];
    const content = parsed[field];

    if (!definition) {
      throw new Error(`Missing section definition for ${field}.`);
    }

    if (typeof content !== "string" || content.trim().length < 80) {
      throw new Error(`Claude response content is too short for ${definition.title}.`);
    }

    return {
      title: definition.title,
      icon: definition.icon,
      content: content.trim(),
    };
  });

  const yearlySection = sections[5];
  const finalSection = sections[6];
  const currentYear = getCurrentYear();

  if (!yearlySection?.content.includes(String(currentYear))) {
    throw new Error("Claude yearly section is missing the current year.");
  }

  const requiredDisclaimer =
    locale === "en"
      ? "This report was generated by AI and is intended for reference only."
      : "본 리포트는 AI가 생성한 참고용 콘텐츠입니다.";

  if (!finalSection?.content.includes(requiredDisclaimer)) {
    throw new Error("Claude report is missing the required disclaimer.");
  }

  return sections;
}

async function delay(milliseconds: number) {
  await new Promise((resolve) => {
    setTimeout(resolve, milliseconds);
  });
}

export function isClaudeConfigured() {
  return Boolean(getAnthropicApiKey());
}

export async function generateClaudeReport(
  input: BirthInput,
  sajuData: SajuData,
  locale: AppLocale = defaultLocale,
): Promise<ReportSectionData[] | null> {
  if (!isClaudeConfigured()) {
    return null;
  }

  const client = getAnthropicClient();
  const system = buildSystemPrompt(locale);
  const userPrompt = buildUserPrompt(input, sajuData, locale);

  for (let retry = 0; retry <= anthropicRetryCount; retry += 1) {
    try {
      const message = await client.messages.create({
        model: anthropicModel,
        max_tokens: anthropicMaxTokens,
        stream: false,
        system,
        messages: [
          {
            role: "user",
            content: userPrompt,
          },
        ],
        output_config: {
          format: {
            type: "json_schema",
            schema: buildStructuredOutputSchema(locale),
          },
        },
      });

      if (message.stop_reason === "max_tokens") {
        throw new Error("Claude response hit max_tokens before completing structured output.");
      }

      if (message.stop_reason === "refusal") {
        throw new Error("Claude refused the report generation request.");
      }

      return parseClaudeSections(extractResponseText(message), locale);
    } catch (error) {
      if (retry === anthropicRetryCount) {
        throw error;
      }

      await delay(anthropicRetryDelayMs);
    }
  }

  return null;
}
